include /usr/local/share/luggage/luggage.make

TITLE=Set\ Safari\ Home\ Page
NAME=SetSafariHomePage
REVERSE_DOMAIN=com.domain
PACKAGE_NAME=${NAME}-${PACKAGE_VERSION}
PACKAGE_VERSION=1.0
PAYLOAD=pack-script-postinstall
