include /usr/local/share/luggage/luggage.make

TITLE=AirWatchAgentRemoval
NAME=RemoveAirWatch
PACKAGE_NAME=${NAME}-${PACKAGE_VERSION}
PACKAGE_ID=${REVERSE_DOMAIN}.${NAME}
REVERSE_DOMAIN=com.domain
PACKAGE_VERSION=1.0
PAYLOAD= \
	pack-script-postinstall \
# DEST="/private/tmp/awrem"
