#!/bin/sh
#==========#
# ABOUT THIS SCRIPT:
# NAME: AppRequestAuto
# SYNOPSIS: Automate App requests via munki and SCOrch
# APP REQUESTED: MacroMates TextMate 2
#==========#
# HISTORY:
# Version 1.0
# Created by Scott Anderson
# Creation Date 7/21/16
#==========#
# ADDITIONAL INFO:
#==========#
# PATH
#==========#
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki
export PATH
#==========#
# VARIABLES
#==========#
# Get current AD computer object name sans $
ADComp="$(dsconfigad -show | awk '/Computer Account/ {print $4}'| tr '[:lower:]' '[:upper:]' | tr -d \$)"
# Get console user
userName="$(ls -la /dev/console | awk '{print $3}')"
# Remote cifs path
cifsPath="cifs://path/to/network/share"
# App Requested
appRequest="AppNameHere"
# Path to file
appReqPath="/Volumes/path"
# App Request Filename
appReqTxt="MacRequest.txt"
# App request failed
appFail="${userPath}/${appRequest}-failed.txt"
# App request succeeded
appSuccess="${userPath}/${appRequest}-succeeded.txt"
# App AD Group
appADGroup="MacLicense-AppRequested"
#==========#
# FUNCTIONS
#==========#
# Display success dialog
success () {
  osascript <<EOT
    tell app "System Events"
      display dialog "$1" buttons {"OK"} default button 1 with icon note with title "Success"
      return  -- Suppress result
    end tell
EOT
}
# Display prompt to request
prompt () {
  osascript <<EOT
    tell app "System Events"
      text returned of (display dialog "$1" default answer "$2" buttons {"OK"} default button 1 with title "Reason for Request")
    end tell
EOT
}

requestReason="$(prompt 'Please provide a reason for the software request:' 'Please provide a Business Justification')"

#==========#
# COMMANDS
#==========#
if [[ ! -e "${appReqPath}/${appReqTxt}" ]]; then
  echo "creating file"
touch "${appReqPath}/${appReqTxt}"
fi

echo "Attempting to write to file"
sudo -u "${userName}" echo "${userName} \ ${ADComp} \ ${appRequest} \ ${appADGroup} \ ${requestReason}" >> "${appReqPath}/${appReqTxt}"
sleep 10
diskutil umount force "${appReqPath}"
success "The app request for ${appRequest} succeeded. Please look for an email containing the  IT ticket number"

exit 0
