#!/bin/bash
#==========#
# ABOUT THIS SCRIPT:
# NAME: DefaultAdmin
# SYNOPSIS: This script will create the local admin account
#==========#
# HISTORY:
# Version 1.7
# Created by Scott Anderson on 11/09/16
# Revision Date
#==========#
# ADDITIONAL INFO:
#==========#
# PATH
#==========#
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki
export PATH
#==========#
# VARIABLES
#==========#
source="/private/tmp/defaultadmin"
userImage="/Library/User Pictures/Instruments/Turntable.tif" #<------CHANGE HERE
madmin_USER="admin"        #<------CHANGE HERE
madmin_PASS="P@ssw0rdHERE" #<------CHANGE HERE
madmin_UID="299"
madmin_NAME="${madmin_USER}"
madmin_HOME="/Users/${madmin_USER}"

#==========#
# COMMANDS
#==========#
# Create New Account Test
sysadminctl -addUser ${madmin_USER} -fullName ${madmin_NAME} -UID ${madmin_UID} \
-shell bash -password ${madmin_PASS} -home ${madmin_HOME} -admin -picture "${userImage}"
dseditgroup -o edit -a ${madmin_USER} -t user admin
dscl . -create /Users/${madmin_USER} IsHidden 1
#dscl . -passwd /Users/"${madmin_USER}" ${madmin_PASS}
# chown and chmod all created files
chown -R ${madmin_USER}:admin "$madmin_HOME"
#Add local account to admin groups
dscl . -append /Groups/admin GroupMembership "$madmin_USER"

# Copy, chmod and chown assets
#mkdir -p "${madmin_PREF}"
#cp "${source}/com.apple.dock.plist" "$madmin_PREF/" &>/dev/null
#cp "${source}/com.apple.Terminal.plist" "$madmin_PREF/" &>/dev/null
#cp "${source}/com.apple.finder.plist" "$madmin_PREF/" &>/dev/null
#cp "${source}/com.apple.SetupAssistant.plist" "$madmin_PREF/" &>/dev/null
#chown -R ${madmin_USER}:admin ${madmin_HOME}
#chmod -R 600 "${madmin_PREF}"/com.apple.dock.plist
#chmod -R 600 "${madmin_PREF}"/com.apple.finder.plist
#chmod -R 600 "${madmin_PREF}"/com.apple.Terminal.plist
#chmod -R 700 "${madmin_PREF}"/com.apple.SetupAssistant.plist

# Set Default Background
#if [[ ! -d "${madmin_DOCK}" ]]; then
#  mkdir -p "${madmin_DOCK}"
#  chown -R ${madmin_USER}:admin ${madmin_HOME}
#  cp "${source}/desktoppicture.db" "${madmin_DOCK}/"
#else
#  rm "${madmin_DOCK}/desktoppicture.db"
#  cp "${source}/desktoppicture.db" "${madmin_DOCK}/"
#  chown ${madmin_USER}:admin "${madmin_DOCK}/desktoppicture.db"
#fi
#killall -HUP -c Dock &> /dev/null
#osascript -e 'delay 1.0' -e 'tell application "Dock" to activate'

touch /var/db/.AppleSetupDone

#touch "${madmin_PREF}/com.apple.SetupAssistant.plist"
#defaults write "${madmin_PREF}"/com.apple.SetupAssistant DidSeeCloudSetup -bool true
#defaults write "${madmin_PREF}"/com.apple.SetupAssistant DidSeeSiriSetup -bool true
#defaults write "${madmin_PREF}"/com.apple.SetupAssistant GestureMovieSeen none
#defaults write "${madmin_PREF}"/com.apple.SetupAssistant LastSeenCloudProductVersion "${sw_vers}"
#defaults write "${madmin_PREF}"/com.apple.SetupAssistant LastSeenBuddyBuildVersion "${sw_build}"
#chown -R ${madmin_USER}:admin ${madmin_HOME}
#chmod 700 "${madmin_PREF}/com.apple.SetupAssistant.plist"

rm -rf ${source} &>/dev/null


exit 0
