#!/bin/sh

SOURCE="/private/tmp/munkilogs"

/bin/mkdir -p /usr/local/scripts/tools &>/dev/null
/bin/cp ${SOURCE}/CreateMunkiLogs /usr/local/scripts/tools/ &>/dev/null
/bin/rm -rf ${SOURCE} &>/dev/null
