#!/bin/bash
OutlookVer="$(defaults read "/Applications/Microsoft Outlook.app/Contents/Info.plist" CFBundleShortVersionString)"
PkgRcpt="/var/db/receipts/com.microsoft.package.Microsoft_Outlook.app.plist"

#Compare Outlook Version needed to install
if [[ -e "$PkgRcpt" ]] && [[ "$OutlookVer" < "15.18" ]]; then 
	echo "Outlook update is required"
    exit 0
else 
    echo "Outlook update is not required"
	exit 1
fi