#!/bin/bash
PwrPtVer="$(defaults read "/Applications/Microsoft PowerPoint.app/Contents/Info.plist" CFBundleShortVersionString)"
PkgRcpt="/var/db/receipts/com.microsoft.package.Microsoft_PowerPoint.app.plist"

#Compare Outlook Version needed to install
if [[ -e "$PkgRcpt" ]] && [[ "$PwrPtVer" < "15.18" ]]; then 
	echo "PowerPoint update is required"
    exit 0
else 
    echo "PowerPoint update is not required"
	exit 1
fi