#!/bin/bash
#==========#
# ABOUT THIS SCRIPT:
# NAME: Uninstall Munki
# SYNOPSIS: Uninstall all files/folders involving Munki.
#==========#
# HISTORY:
# Version 1.0
# Created by Scott Anderson on 12/12/17
# Revision Date
#==========#
# PATH
#==========#
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH
#==========#
# VARIABLES
#==========#

LibLD="/Library/LaunchDaemons"
LibLA="/Library/LaunchAgents"
LibAS="/Library/Application Support"
userName="$(ls -la /dev/console | awk '{print $3}')"

pkgForget=(
  com.yp.TeamViewerHost
  com.teamviewer.teamviewer12AuthPlugin
  com.teamviewer.teamviewer12PriviledgedHelper
  com.teamviewer.teamviewerhost12
  com.teamviewer.teamviewerhost12Agent
  com.teamviewer.teamviewerhost12Font
  com.teamviewer.teamviewerhost12Restarter
)

#==========#
# COMMANDS
#==========#
launchctl unload -w "${LibLA}"/com.teamviewer.*
launchctl unload -w "${LibLD}"/com.teamviewer.*
#launchctl unload "${LibLA}"/com.teamviewer.Helper.plist
killall TeamViewer_Service
killall TeamViewer_Desktop
killall TeamViewerHost

rm -rf "${LibAS}"/"TeamViewer Host"
rm -rf "/Applications/TeamViewerHost.app"
rm -f "${LibLA}"/com.teamviewer.*
rm -f "${LibLD}"/com.teamviewer.*
rm -f /Users/"${userName}"/Library/Preferences/com.teamviewer.teamviewer.preferences.plist
rm -f /Users/"${userName}"/Library/Preferences/com.teamviewer.TeamViewerHost.plist

for pkgid in ${pkgForget[@]}; do
       pkgutil --forget "${pkgid}" 2>&1
done

exit 0
