include /usr/local/share/luggage/luggage.make

TITLE=UpdateSUS
NAME=UpdateSUS
PACKAGE_NAME=${NAME}-${PACKAGE_VERSION}
PACKAGE_ID=${REVERSE_DOMAIN}.${NAME}
REVERSE_DOMAIN=com.domain
PACKAGE_VERSION=1.03
PAYLOAD= \
	pack-script-postinstall \
