#!/bin/bash
#==========#
# ABOUT THIS SCRIPT:
# NAME: Uninstall Munki
# SYNOPSIS: Uninstall all files and daemons involving macstats.
#==========#
# HISTORY:
# Version 1.0
# Created by Scott Anderson on 12/29/17
# Revision Date
#==========#
# PATH
#==========#
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH
#==========#
# VARIABLES
#==========#
LibLD="/Library/LaunchDaemons"
asset1="com.yp.corp.macstats-update.plist"
asset2="macstats"
ULC="/usr/local/corp"
#==========#
# COMMANDS
#==========#
# Unload launchdaemon
if [[ -e "${LibLD}"/"${asset1}" ]]; then
	msproc="$(launchctl list | awk '/com.yp.corp.macstats-update/ {print $3}')"
	if [ "${msproc}" = "com.yp.corp.macstats-update" ];then
		launchctl stop "${LibLD}"/"${asset1}" 2>/dev/null
		launchctl unload "${LibLD}"/"${asset1}" 2>/dev/null
	fi
fi
# Remove macstats daemons and files
rm -f "${LibLD}"/"${asset1}" 2>/dev/null
rm -f "${ULC}"/"${asset2}" 2>/dev/null

# Forget pkg receipts
pkgForget=(
  com.yp.MacStatsClient
)

for pkgid in ${pkgForget[@]}; do
       pkgutil --forget "${pkgid}" 2>&1
done

exit 0
