include /usr/local/share/luggage/luggage.make

TITLE=Office2016Dock
NAME=Office2016Dock
PACKAGE_NAME=${NAME}-${PACKAGE_VERSION}
PACKAGE_ID=${REVERSE_DOMAIN}.${NAME}
REVERSE_DOMAIN=com.domain
PACKAGE_VERSION=1.01
PAYLOAD= \
	pack-script-postinstall \
