#!/bin/bash
#==========#
# ABOUT THIS SCRIPT:
# NAME: Munki Health Check remove
# SYNOPSIS: This will run as a local LaunchDaemon
# exit status not 0 means no installation necessary
#==========#
# HISTORY:
# Version 1.2
# Created by Scott Anderson on 8/22/2016
# Revision Date 11/08/2017
#==========#
# PATH
#==========#
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki
export PATH
#==========#
# VARIABLES
#==========#
TARGET_VOL="$3"
LibLD="/Library/LaunchDaemons"
LibLA="/Library/LaunchAgents"
munkiHC="/usr/local/corp/munkihc"
munkiHCLD="com.yp.corp.munki-healthcheck.plist"
#==========#
# COMMANDS
#==========#
# Unload launchdaemon
if [[ -e "$LibLD"/"${munkiHCLD}" ]]; then
	chflags -f noschg "$LibLD"/"${munkiHCLD}"
	mHCproc="$(launchctl list | awk '/com.yp.corp.munki-healthcheck/ {print $3}')"
	if [ "${mHCproc}" = "com.yp.corp.munki-healthcheck" ];then
		launchctl stop "$LibLD"/"${munkiHCLD}" 2>/dev/null
		launchctl unload "$LibLD"/"${munkiHCLD}" 2>/dev/null
	fi

fi
# Unload munki LaunchDaemons
#com.googlecode.munki.logouthelper
#com.googlecode.munki.managedsoftwareupdate-check
#com.googlecode.munki.managedsoftwareupdate-manualcheck
#com.googlecode.munki.authrestartd
#com.googlecode.munki.managedsoftwareupdate-install
#com.googlecode.munki.app_usage_monitor
#launchctl unload "${LibLD}"/com.googlecode.munki.* 2>/dev/null
# Check for MSC msuprocess
# Detected munki processes
#/Applications/Managed Software Center.app/Contents/MacOS/Managed Software Center
#/usr/bin/python /usr/local/munki/supervisor --timeout 43200 -- /usr/local/munki/managedsoftwareupdate --m
#/usr/bin/python /usr/local/munki/managedsoftwareupdate --manualcheck
#/usr/bin/python /usr/local/munki/ptyexec /usr/sbin/softwareupdate --verbose -d -a

msuproc1="$(ps -eo pid=pid,command=cmnd | cut -f2- -d ' ' | awk '$2~/python/' | awk '$3~/managedsoftwareupdate/' | awk '{ print $1 }')"
msuproc2="$(ps -eo pid=pid,command=cmnd | cut -f2- -d ' ' | awk '$2~/python/' | awk '$3~/supervisor/' | awk '{ print $1 }')"
msuproc3="$(ps -eo pid=pid,command=cmnd | cut -f2- -d ' ' | awk '$2~/python/' | awk '$3~/ptyexec/' | awk '{ print $1 }')"
msuproc4="$(ps -ax | grep -v grep | grep -i "Managed Software Center" | awk '{print $1}')"

process=(
$msuproc1
$msuproc2
$msuproc3
$msuproc4
)

kill "${process[@]}"
echo "Kill PID ${process[@]}"

exit 0
