#!/bin/bash

munkild="/Library/LaunchDaemons/com.domain.munki-healthcheck.plist"
munkihc="/usr/local/scripts/munkihc"

/bin/launchctl load "$munkild" 2>/dev/null
/bin/launchctl start "$munkild" 2>/dev/null
/usr/bin/chflags schg "$munkild" 2>/dev/null
/usr/bin/chflags schg "$munkihc" 2>/dev/null

exit 0
