#!/usr/bin/python
#==========#
# ABOUT THIS SCRIPT:
# NAME: MunkiAdditions
# SYNOPSIS: 
#==========#
# HISTORY:
# Version 3.4.3
# Created by Heig Gregorian 
# Revised by Scott Anderson
# Revision Date 10/13/16
#==========#
# ADDITIONAL INFO:
#==========#
import sys
import os
import subprocess
import stat
preflight_dir = '/usr/local/munki/preflight.d'
for script in os.listdir(preflight_dir):
    st = os.stat(os.path.join(preflight_dir, script))
    mode = st.st_mode
    if not mode & stat.S_IWOTH:
        try:
            subprocess.call([os.path.join(preflight_dir, script),
                            sys.argv[1]],
                            stdin=None)
        except OSError:
            print "Something went wrong!"
    else:
        print script + " is not executable or has bad permissions"
