#!/bin/sh

osvers=$(sw_vers -productVersion | awk -F. '{print $2}')
sw_vers=$(sw_vers -productVersion)
sw_build=$(sw_vers -buildVersion)
madmin="admin"
mahome="/var/home/${madmin}"

touch /var/db/.AppleSetupDone

	for USER_TEMPLATE in "/System/Library/User Template"/*
	  do
	    /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool true
			/usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeSiriSetup -bool true
	    /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
	    /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion "${sw_vers}"
	    /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant LastSeenBuddyBuildVersion "${sw_build}"
	  done

if [ ! -d "${mahome}" ]; then
	bin/mkdir -p "${mahome}"/Library/Preferences
	/usr/sbin/chown "${madmin}" "${mahome}"/Library
	/usr/sbin/chown "${madmin}" "${mahome}"/Library/Preferences
else
	/usr/bin/defaults write "${mahome}"/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool true
	/usr/bin/defaults write "${mahome}"/Library/Preferences/com.apple.SetupAssistant DidSeeSiriSetup -bool true
	/usr/bin/defaults write "${mahome}"/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
	/usr/bin/defaults write "${mahome}"/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion "${sw_vers}"
	/usr/bin/defaults write "${mahome}"/Library/Preferences/com.apple.SetupAssistant LastSeenBuddyBuildVersion "${sw_build}"
	/usr/sbin/chown macadmin:admin "${mahome}"/Library/Preferences/com.apple.SetupAssistant.plist
	/bin/chmod 700 "${mahome}"/Library/Preferences/com.apple.SetupAssistant.plist
fi


	for USER_HOME in /Users/*
	  do
	    USER_UID=`basename "${USER_HOME}"`
	    if [ ! "${USER_UID}" = "Shared" ]; then
				if [ ! -d "${USER_HOME}"/Library/Preferences ]; then
			        /bin/mkdir -p "${USER_HOME}"/Library/Preferences
			        /usr/sbin/chown "${USER_UID}" "${USER_HOME}"/Library
			        /usr/sbin/chown "${USER_UID}" "${USER_HOME}"/Library/Preferences
				fi
				if [ -d "${USER_HOME}"/Library/Preferences ]; then
	    		/usr/bin/defaults write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool true
		  		/usr/bin/defaults write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant DidSeeSiriSetup -bool true
	    		/usr/bin/defaults write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
	    		/usr/bin/defaults write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion "${sw_vers}"
	    		/usr/bin/defaults write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant LastSeenBuddyBuildVersion "${sw_build}"
	    		/usr/sbin/chown "${USER_UID}":40000 "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant.plist
	    		/bin/chmod 700 "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant.plist
	    	fi
	fi
	done

exit 0
