#!/bin/bash
pkgName="DefaultAdmin"
pkgVersion="1.0"
domain="domain"
identifier="com.${domain}.${pkgName}"
tmpDir="/private/tmp/defaultadmin/"
PATH=/usr/bin:/bin:/usr/sbin:/sbin export PATH

projectfolder=$(dirname $0)

pkgbuild --root payload --install-location / \
--scripts scripts --identifier "${identifier}" \
--version "${pkgVersion}" "${pkgName}-${pkgVersion}.pkg"

#productbuild --package "${pkgName}".pkg "${pkgName}"-"${pkgVersion}".pkg
#rm "${pkgName}".pkg
#hdiutil create \
#-volname "${pkgName}"-"${pkgVersion}" \
#-srcfolder "${pkgName}"-"${pkgVersion}".pkg \
#-ov \
#"${projectfolder}"/"${pkgName}"-"${pkgVersion}".dmg
#rm "${pkgName}"-"${pkgVersion}".pkg
