#!/bin/bash
pkgName="DisableiCloudDiagsSetup"
pkgVersion="1.0"
pkgbuild --root payload --install-location "/private/tmp/DisableiCloudDiagsSetup/" \
--scripts scripts --identifier com.domain.$pkgName \
--version $pkgVersion $pkgName-$pkgVersion.pkg

hdiutil create \
-volname $pkgName-$pkgVersion \
-srcfolder $pkgName-$pkgVersion.pkg \
-ov \
$pkgName-$pkgVersion.dmg
