#!/bin/sh
#==========#
# ABOUT THIS SCRIPT:
# NAME: auto_adbind
# SYNOPSIS: Rebind unbound hosts to Active Directory
#==========#
# HISTORY:
# Version 1.1
# Created by Scott Anderson
# Creation Date
# Revised by Scott Anderson
# Revision Date 060121
#$1: Full Path to Package
#$2: Full Path to target installation directory: /Applications
#$3: Mountpoint of installation disk: / or /Volumes/External_Drive
#$4: Root directory of currently booted system

#==========#
# ADDITIONAL INFO:
#==========#
# PATH
#==========#
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH
#==========#
# VARIABLES
#==========#
UserName="$(ls -la /dev/console | awk '{print $3}')"
Today=$(date "+%m%d%Y")
Time=$(date "+%H%M%S")
ARD_bup="$3/Users/${UserName}/dev/eus-projects-mac/ardBup/Archives/$Today$Time-ARDBackup"
ARD_db="/var/db/RemoteManagement"
ARD_lib="/Library/Preferences/com.apple.RemoteDesktop.plist"
ARD_remMgmt="/Library/Preferences/com.apple.remoteManagement.plist"
ARD_usr="/Users/${UserName}/Library/Containers/com.apple.RemoteDesktop/Data/Library/Preferences/com.apple.RemoteDesktop.plist"
ARD_appsprt="/Library/Application Support/Apple/Remote Desktop/"
#ARD_usr_appsprt="/Users/$UserName/Library/Application Support/Remote Desktop/"
ARD_agentPrefs="/Library/Preferences/com.apple.ARDAgent.plist"
#==========#
killall "Remote Desktop"
mkdir -p "${ARD_bup}/var/db/RemoteManagement"
cp -pR "${ARD_db}" "${ARD_bup}/var/db/RemoteManagement"
sleep 2
mkdir -p "${ARD_bup}/Library/Preferences/"
cp -pR "${ARD_lib}" "${ARD_bup}/Library/Preferences/"
sleep 2
mkdir -p "${ARD_bup}/Library/Preferences/"
cp -pR "${ARD_remMgmt}" "${ARD_bup}/Library/Preferences/"
sleep 2
mkdir -p "${ARD_bup}/Users/${UserName}/Library/Containers/com.apple.RemoteDesktop/Data/Library/Preferences/"
cp -pR "${ARD_usr}" "${ARD_bup}/Users/${UserName}/Library/Containers/com.apple.RemoteDesktop/Data/Library/Preferences/"
sleep 2
mkdir -p "${ARD_bup}/Library/Application Support/Apple/Remote Desktop/"
cp -pR "${ARD_appsprt}" "${ARD_bup}/Library/Application Support/Apple/Remote Desktop/"
sleep 2
mkdir -p "${ARD_bup}/Library/Preferences/"
cp -pR "${ARD_agentPrefs}" "${ARD_bup}/Library/Preferences/"
sleep 2
echo "Copy complete."
