#!/bin/bash
#==========#
# ABOUT THIS SCRIPT:
# NAME: macOS upgrade link
# SYNOPSIS: Launches Mac App Store link for OS upgrade
#==========#
# HISTORY:
# Version 1.0
# Created by Scott Anderson
# Creation Date 04/14/17
#==========#
# ADDITIONAL INFO:
#==========#
# PATH
#==========#
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki
export PATH
#==========#
# VARIABLES
#==========#
appID="macappstore://itunes.apple.com/us/app/macos-sierra/id1127487414?mt=12"
#==========#
# COMMANDS
#==========#
#Open Mac App Store
open "$appID"
exit 0
